query buscarVarias($busqueda: BuscarPersonaDto!) {
  buscarVariasPersonas(busqueda: $busqueda) {
    usuario
    nombre
    telefono
    correo
    permisos
  }
}

mutation crearUna($data: CrearPersonaDto!) {
  crearUnaPersona(data: $data) {
    _id
    contrasena
    nombre
    telefono
    correo
  }
}

query conectar($data: ConexionDto!) {
  conectar(data: $data) {
    token
  }
}

query demoAuth {
  demoAuth
}
